### ISSUE TITLE
Error After Installing..

### ISSUE THREAD

**Issue by SandyMaull** [pavolelsig/passthrough_helper_manjaro#1]
/usr/bin/mkinitcpio: line 265: /etc/mkinitcpio.d/linux52.preset: No such file or directory
==> ERROR: Failed to load preset: `/etc/mkinitcpio.d/linux52.preset'
I get this result when installing the ./manjaro_help.sh ...

![Screenshot_20191130_003152](https://user-images.githubusercontent.com/14269978/69881734-df956f00-1308-11ea-8eb6-1958c471d8ec.png)

**Comment by pavolelsig** [comment]
I know it's not mentioned in the guide, but the script was only tested on the latest Manjaro release. I see in your case, it's looking for /etc/mkinitcpio.d/linux52.preset and on my system, it's linux53. Maybe you can try the latest Manjaro 18. Btw: If you are trying to do GPU passthrough on a laptop, it very unlikely to actually work.
