### ISSUE TITLE
The Pinned Comment on the manjaro gpu passthrough video

### ISSUE THREAD

**Issue by yoda123456** [pavolelsig/passthrough_helper_manjaro#10]
hey pavolelsig gotta say your really awesome and have fantastic tutorials!i want to use this for manjro just really confused about this one thing in your manjaro gpu passthrough guide's pinned comment you said this:

 If you end up with a black screen on bootup, do this:

Press ALT CTRL and F2 at the same time

Login into the command line and type 

startx

Open Manjaro Settings Manager

Go to Hardware Configuration and uninstall any other drivers that are installed by right clicking and uninstalling

Reboot

im just confused as to what drivers are being referred in this comment and if this will defiantly happen or just happens for some users, and thanks in advance for any help with this question from anyone!

**Comment by pavolelsig** [comment]
You probably won't run into this issue. It was pretty rare to begin with and I think it was fixed since then.

**Comment by yoda123456** [comment]
Thanks alot! Did the passthrough without any issues, can't thank ya enough for all the tutorials and everything including this script man!
