### ISSUE TITLE
./manjaro_help.sh: line 48: [: rolling: integer expression expected

### ISSUE THREAD

**Issue by cindrmon** [pavolelsig/passthrough_helper_manjaro#4]
Is there some kind of typo in the shellscript you provided? It would stop here and just terminate. Please help.
![Snapshot_Nov20::174948](https://user-images.githubusercontent.com/37018771/98525854-064b7c00-22b4-11eb-8a79-67437d11cdcc.png)

**Comment by pavolelsig** [comment]
Thanks for pointing this out. I'll take a look at it and fix it. The script should should still work just fine. It did finish successfully. The problem is at the very end where is checks for for older versions of Manjaro.

**Comment by pavolelsig** [comment]
Fixed
